# Generated by Django 4.1.7 on 2023-04-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationUserName', models.CharField(max_length=255)),
                ('applicationPhone', models.CharField(max_length=255)),
                ('applicationTelegramm', models.CharField(max_length=255)),
                ('applicationStudentsGroup', models.CharField(max_length=255)),
                ('applicationDirection', models.CharField(max_length=255)),
                ('applicationDescriptionDirection', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarEventDateUNIX', models.CharField(max_length=255)),
                ('calendarEventTitle', models.CharField(max_length=255)),
                ('calendarEventImage', models.ImageField(max_length=255, upload_to='')),
                ('calendarEventDateNORMAL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeryGroup', models.CharField(max_length=100)),
                ('galeryImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=300)),
                ('newsContent', models.TextField(null=True)),
                ('newsImage', models.ImageField(upload_to='static/images/')),
                ('newsEventName', models.CharField(max_length=255)),
            ],
        ),
    ]
