# Generated by Django 4.1.7 on 2023-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='galeryImage',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
